export const mockData = {
  project: {
    name: 'Quantum VPN Security Evaluation Platform',
    description: 'Enterprise-grade command center for evaluating VPN resilience, attack simulations, and traffic analysis within isolated lab environments.',
    team: ['Aaditya V', 'Darshan N', 'BasavaPrabhu', 'Bhargavi'],
    guide: 'Bhavana',
    status: 'Active Experiment',
    currentExperiment: 'Hybrid Tunnel Resilience Test',
    vpnStatus: 'Connected',
  },
  stats: [
    { label: 'Total Experiments', value: '128', change: '+12%' },
    { label: 'Successful Runs', value: '114', change: '+8%' },
    { label: 'Failed Runs', value: '14', change: '-3%' },
    { label: 'Active VPN', value: 'Hybrid', change: 'Stable' },
    { label: 'Active Attack', value: 'Downgrade', change: 'Blocked' },
    { label: 'Current Algorithm', value: 'Kyber + AES-256', change: 'Quantum-safe' },
  ],
  timeline: [
    { title: 'VPN Started', time: '08:20', detail: 'Hybrid link established', color: 'green' },
    { title: 'Attack Executed', time: '08:24', detail: 'Replay attack launched', color: 'red' },
    { title: 'Handshake Completed', time: '08:27', detail: 'Cipher negotiation finished', color: 'blue' },
    { title: 'Report Generated', time: '08:35', detail: 'Executive summary exported', color: 'yellow' },
  ],
  vpnConfigs: [
    {
      name: 'Classical VPN',
      algorithm: 'OpenVPN + AES-128',
      tunnelStatus: 'CONNECTED',
      cipher: 'AES-128-GCM',
      handshakeTime: '38 ms',
      connectionTime: '1.2 s',
      encryptionStandard: 'TLS 1.2',
      sessionDuration: '08:20:14',
      statusColor: 'green',
    },
    {
      name: 'PQ VPN',
      algorithm: 'WireGuard + Kyber',
      tunnelStatus: 'INITIALIZING',
      cipher: 'ML-KEM + ChaCha20',
      handshakeTime: '21 ms',
      connectionTime: '0.9 s',
      encryptionStandard: 'TLS 1.3',
      sessionDuration: '03:42:11',
      statusColor: 'yellow',
    },
    {
      name: 'Hybrid VPN',
      algorithm: 'Hybrid TLS + PQ',
      tunnelStatus: 'CONNECTED',
      cipher: 'Kyber + AES-256',
      handshakeTime: '17 ms',
      connectionTime: '0.7 s',
      encryptionStandard: 'TLS 1.3',
      sessionDuration: '05:12:09',
      statusColor: 'green',
    },
  ],
  attackOptions: ['MITM', 'Replay Attack', 'Downgrade Attack', 'Negotiation Manipulation', 'Packet Injection', 'Packet Delay', 'Packet Drop'],
  packets: {
    captured: 18432,
    modified: 128,
    handshakeMessages: 92,
    negotiationMessages: 41,
    encryptedPackets: 17320,
    droppedPackets: 14,
    liveFlow: [12, 18, 15, 20, 22, 19, 24],
    trafficTimeline: [8, 10, 9, 15, 16, 14, 20],
    packetTypes: [45, 20, 15, 12, 8],
    recentPackets: [
      { time: '08:30:11', source: 'Client VM', destination: 'VPN Server', protocol: 'TCP', status: 'Forwarded', size: '1.4 KB' },
      { time: '08:30:17', source: 'Kali VM', destination: 'Client VM', protocol: 'UDP', status: 'Flagged', size: '812 B' },
      { time: '08:30:21', source: 'VPN Server', destination: 'Internet', protocol: 'TLS', status: 'Encrypted', size: '2.3 KB' },
    ],
  },
  performance: {
    handshake: [24, 20, 19, 18, 17, 16, 15],
    latency: [48, 42, 39, 41, 38, 36, 35],
    cpu: [62, 64, 60, 58, 59, 57, 56],
    memory: [71, 73, 72, 70, 69, 68, 67],
    bandwidth: [890, 910, 920, 940, 955, 965, 970],
    packetRate: [1300, 1340, 1380, 1420, 1450, 1480, 1500],
    throughput: [420, 430, 442, 451, 458, 462, 468],
  },
  logs: {
    vpn: [
      { time: '08:20:01', module: 'VPN Manager', level: 'SUCCESS', description: 'Tunnel negotiated successfully', status: 'Healthy' },
      { time: '08:24:33', module: 'VPN Manager', level: 'WARNING', description: 'Replay attempt observed', status: 'Mitigated' },
    ],
    attack: [
      { time: '08:23:55', module: 'Attack Engine', level: 'ERROR', description: 'Packet injection blocked', status: 'Blocked' },
      { time: '08:24:10', module: 'Attack Engine', level: 'INFO', description: 'Downgrade attack simulation initiated', status: 'Running' },
    ],
    system: [
      { time: '08:19:56', module: 'Health Monitor', level: 'SUCCESS', description: 'VM heartbeat detected', status: 'OK' },
      { time: '08:25:17', module: 'Health Monitor', level: 'CRITICAL', description: 'Disk pressure warning', status: 'Investigate' },
    ],
    error: [
      { time: '08:26:44', module: 'Packet Filter', level: 'WARNING', description: 'Minor packet loss observed', status: 'Monitor' },
    ],
  },
  results: [
    { test: 'Classical VPN Handshake', vpnType: 'Classical VPN', attack: 'None', expected: 'Pass', observed: 'Pass', status: 'PASS' },
    { test: 'PQ VPN Handshake', vpnType: 'PQ VPN', attack: 'None', expected: 'Pass', observed: 'Pass', status: 'PASS' },
    { test: 'Hybrid VPN Handshake', vpnType: 'Hybrid VPN', attack: 'None', expected: 'Pass', observed: 'Pass', status: 'PASS' },
    { test: 'Downgrade', vpnType: 'Hybrid VPN', attack: 'Downgrade', expected: 'Blocked', observed: 'Blocked', status: 'BLOCKED' },
    { test: 'Replay', vpnType: 'PQ VPN', attack: 'Replay', expected: 'Blocked', observed: 'Blocked', status: 'BLOCKED' },
    { test: 'MITM', vpnType: 'Hybrid VPN', attack: 'MITM', expected: 'Detected', observed: 'Detected', status: 'DETECTED' },
  ],
  comparison: {
    classical: { handshake: 38, cpu: 68, memory: 74, bandwidth: 790, latency: 48, replay: 'Weak', downgrade: 'Weak', mitm: 'Limited', negotiation: 'Basic', algorithm: 'AES-128' },
    pq: { handshake: 21, cpu: 62, memory: 69, bandwidth: 900, latency: 37, replay: 'Strong', downgrade: 'Strong', mitm: 'Strong', negotiation: 'Advanced', algorithm: 'Kyber + AES' },
    hybrid: { handshake: 17, cpu: 59, memory: 67, bandwidth: 970, latency: 35, replay: 'Very Strong', downgrade: 'Very Strong', mitm: 'Very Strong', negotiation: 'Robust', algorithm: 'Kyber + AES-256' },
  },
};
